spring:
  application:
    name: kill-batch-system
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:org/springframework/batch/core/schema-drop-postgresql.sql
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

cors:
  allowed-origins: localhost:3000

log:
  config:
    error:
      path: logs/dev/error
      filename: application-dev-error
    trace:
      path: logs/dev/trace
      filename: trace
    maxHistory: 30
    totalSizeCap: 1GB