spring:
  application:
    name: kill-batch-system
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:org/springframework/batch/core/schema-drop-postgresql.sql
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show_sql: true                    # SQL 출력
      hibernate.format_sql: true                  # SQL 포맷팅
      hibernate.use_sql_comments: true            # 어떤 엔티티에서 실행된 SQL인지 주석 표시
      hibernate.highlight_sql: true              # SQL 구문 하이라이팅 (콘솔에서)
      hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 값까지 출력
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  config:
    import: optional:file:.env[.properties]

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo

summary:
  scheduler:
    batch-size: 2          # 한 번 실행당 가져올 건수
    max-per-tick: 200       # 한 번 실행에서 최대 처리 총량 (여러 배치 루프)
    throttle-ms: 300        # OpenAI 호출 사이 간격 (과금/레이트리밋 대비)

crawler:
  throttleMs: 200
  list:
    wfootball: "https://m.sports.naver.com/wfootball/news/list?date={date}&page={page}"

espn:
  json:
    epl-url: "https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1/news"
  limit: 20
  max-items: 20

goal:
  sitemap-url: "https://www.goal.com/kr/google-news/page"
  max-items: 20
  recent-hours: 48
  throttleMs: 400
  min-content-length: 180

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    access-token-validity-seconds: 900 # 15분
    refresh-token-validity-seconds: 604800 # 7일

hancut:
  admin:
    nickname: ${ADMIN_NICKNAME}
    password: ${ADMIN_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}

scheduler:
  naver:
    cron: "0 10 * * * *"
  goal:
    cron: "0 30 * * * *"
  espn:
    cron: "0 0 */6 * * *"

file:
  upload:
    profiles:
      path: profiles/images/
      allowed-extensions: jpg,jpeg,png,gif,webp
      max-size: 5242880

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus