## 🩹 Hotfix PR

### 📋 개요
이번 PR은 **긴급 수정(hotfix)** 브랜치로부터 생성된 PR입니다.
`main` 브랜치에 바로 병합되어 서비스 장애나 치명적 버그를 신속히 수정합니다.

---

### 🐞 수정 내용
- 문제 원인: (예: API 응답 오류, 배포 환경 설정 문제 등)
- 수정 사항: (예: null 체크 추가, 로깅 강화 등)
- 영향 범위: (예: 사용자 로그인, 결제 프로세스 등)

---

### 🔍 테스트 및 검증
- [ ] 수정된 부분에 대한 단위 테스트 작성/수정
- [ ] 로컬 및 staging 환경에서 정상 동작 확인
- [ ] 회귀 테스트(Regression Test) 완료

---

### 🧩 관련 이슈
- 긴급 대응 이슈: #ISSUE_NUMBER

---

### ⚙️ 배포
- [ ] Hotfix 병합 후 develop 브랜치로도 역병합(Back-merge) 필요
- [ ] 배포 승인자 확인 완료

---

  > ⚠️ **주의:** Hotfix 병합 후 develop 브랜치로 **rebase 또는 merge** 작업을 반드시 수행하세요.
