name: 릴리즈 배포
description: develop 브랜치에서 main 브랜치로 배포하기 위한 템플릿
title: "[Release]: "
labels: ["release"]
body:
  - type: input
    id: branch_keyword
    attributes:
      label: "Branch Keyword"
      description: "릴리즈 버전을 영문 소문자로 입력하세요 (예: v1-2-0)"
      placeholder: "예: v1-2-0"
    validations:
      required: true

  - type: textarea
    id: release_summary
    attributes:
      label: "릴리즈 개요"
      description: "이번 릴리즈의 주요 변경 사항을 요약해주세요"
      placeholder: |
        - 신규 기능: 
        - 버그 수정:
        - 리팩터링:
        - 기타:
    validations:
      required: true

  - type: textarea
    id: qa_result
    attributes:
      label: "QA 결과 요약"
      description: "릴리즈 전 QA 결과를 간단히 작성해주세요"
      value: |
        - [ ] 주요 기능 정상 동작 확인
        - [ ] API 응답 정상
        - [ ] 오류 로그 없음
        - [ ] 브라우저/모바일 테스트 완료

  - type: textarea
    id: deploy_plan
    attributes:
      label: "배포 계획"
      description: "배포 일자, 담당자, 대상 환경 등을 명시해주세요"
      value: |
        - 예정 배포일: YYYY-MM-DD
        - 배포 담당자: 
        - 배포 대상 환경: production

  - type: markdown
    attributes:
      value: |
        ---
        ### Branch Keyword
        ${{ inputs.branch_keyword }}
