## 🚀 Release PR

### 📋 개요
이번 PR은 **배포(release)** 브랜치로 병합하기 위한 PR입니다.
`develop` → `main` 병합을 통해 실제 서비스 반영을 준비합니다.

---

### 🔍 변경 사항 요약
- [ ] 기능 검증 완료 (QA 포함)
- [ ] 불필요한 로그, 주석 제거
- [ ] 버전 태그 갱신 (`vX.Y.Z`)
- [ ] 관련 문서 업데이트 (README, API 문서 등)

---

### 🧩 관련 이슈
- 연결된 이슈: #ISSUE_NUMBER

---

### ✅ 체크리스트
- [ ] 코드 리뷰 통과
- [ ] 테스트 전부 통과 (`./gradlew test`)
- [ ] CI/CD 파이프라인 확인 완료
- [ ] 배포 환경 변수 및 시크릿 점검 완료

---

### 🗓️ 배포 일정
- 예정 배포일: YYYY-MM-DD
- 배포 대상 환경: `production`

---

  > ⚠️ **주의:** 배포 PR은 반드시 팀 리뷰 및 QA 완료 후 머지해주세요.
