openapi: 3.0.3
info:
  title: 축구한컷 API
  description: 축구한컷 서비스 API입니다~
  termsOfService: https://hancut.vercel.app/
  contact:
    name: 김준우
    email: junnukim1007@gmail.com
  version: 1.0.0
tags:
  - name: Summary
    description: AI 뉴스 요약 조회 관련 엔드포인트
paths:
  /api/summary:
    get:
      summary: 뉴스 AI 요약 조회
      tags:
        - Summary
      operationId: getAISummaries
      parameters:
        - name: keyword
          in: query
          description: 키워드로 기사 요약을 검색합니다.
          schema:
            type: string
          example: 손흥민
        - name: sourceName
          in: query
          description: 뉴스 출처로 필터링합니다.
          schema:
            $ref: "#/components/schemas/ArticleSource"
          example: ESPN
        - name: sortBy
          in: query
          description: 정렬 기준 (최신순/인기순)
          schema:
            $ref: "#/components/schemas/SortBy"
          example: LATEST
        - name: page
          in: query
          description: 페이지 번호 (0부터 시작)
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
          example: 0
        - name: size
          in: query
          description: 페이지 크기
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
          example: 20
      responses:
        "200":
          description: 뉴스 요약 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageResponse_GetAISummary"
              example:
                cards:
                  - id: 101
                    title: "맨체스터 유나이티드, 리버풀과의 경기서 극적인 승리"
                    summary:
                      - 맨유가 후반 추가시간에 결승골을 넣으며 2-1 승리를 거뒀다.
                      - 리버풀은 경기 초반 주도권을 잡았지만 결정적인 기회를 살리지 못했다.
                      - 브루노 페르난데스가 팀 승리를 이끄는 활약을 펼쳤다.
                    keyword:
                      - 맨체스터 유나이티드
                      - 리버풀
                      - 프리미어리그
                    publishedAt: 2025-09-28T18:30:00Z
                    league: EPL
                    team: Manchester United
                    url: https://example.com/articles/mu-vs-liverpool
                    sourceName: ESPN
                page: 0
                totalPages: 12
                last: false
                size: 20
                numberOfElements: 20
                totalElements: 234
  /api/summary/keywords/top:
    summary: 가장 많이 나온 키워드 TOP 10 조회
    get:
      summary: 가장 많이 나온 키워드 조회
      tags:
        - Summary
      operationId: getTopKeywords
      parameters:
        - name: limit
          in: query
          description: 키워드 개수를 결정합니다.
          example: "10"
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: 키워드 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopKeyword"
              example:
                keyowrd: 손흥민
                count: "12"
components:
  schemas:
    PageResponse_GetAISummary:
      type: object
      properties:
        cards:
          type: array
          items:
            $ref: "#/components/schemas/GetAISummary"
        page:
          type: integer
          format: int32
          minimum: 0
        totalPages:
          type: integer
          format: int32
          minimum: 0
        last:
          type: boolean
        size:
          type: integer
          format: int32
          minimum: 1
        numberOfElements:
          type: integer
          format: int32
          minimum: 0
        totalElements:
          type: integer
          format: int64
          minimum: 0
      required:
        - cards
        - page
        - totalPages
        - last
        - size
        - numberOfElements
        - totalElements
    GetAISummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        summary:
          type: array
          items:
            type: string
        keyword:
          type: array
          items:
            type: string
        publishedAt:
          type: string
          format: date-time
        league:
          type: string
        team:
          type: string
        url:
          type: string
        sourceName:
          $ref: "#/components/schemas/ArticleSource"
        thumbnailUrl:
          type: string
    ArticleSource:
      type: string
      enum:
        - BBC
        - ESPN
        - GOAL
    SortBy:
      type: string
      enum:
        - LATEST
        - POPULAR
    TopKeyword:
      type: object
      properties:
        keyword:
          type: string
        count:
          type: integer
          format: int64
          minimum: 0
      required:
        - keyword
        - count
